# ========================================================================================
# Gate^Flame T1 - build and flash one ESP32-S3 T1 node, then PROVE it reported in.
# (c) 2018-2026 Antwerp Designs | Ionity (Pty) Ltd - TM2 | Policy 986 AED
#
#   tools\T1-BUILD-FLASH.cmd                      (prompts for what it needs)
#   powershell -File t1\scripts\build-flash.ps1 -Port COM8 -Ssid LabNet -Level low
#   ... -NoUpload                                  compile only
#
# The Wi-Fi password is asked for HERE, on this machine, and never leaves it. secrets.h
# is written just for the compile and deleted afterwards (keep it with -KeepSecrets).
# Uses the T1 server's venv for the device token and signing public key, so run
# tools\T1-SERVER.cmd once first. Does not touch E:\.ESP32-MCP in any way.
# ========================================================================================
param(
  [string]$Port = '',
  [string]$Ssid = '',
  [string]$Server = '',
  [ValidateSet('low', 'medium', 'high')][string]$Level = 'low',
  [ValidateSet('opi', 'enabled', 'disabled')][string]$Psram = 'opi',
  [string]$StaticIp = '',
  [switch]$UsbCdc,
  [switch]$NoUpload,
  [switch]$KeepSecrets
)
$ErrorActionPreference = 'Stop'
$t1 = Resolve-Path (Join-Path $PSScriptRoot '..')
$sketch = Join-Path $t1 'firmware\GF_T1_Node'
$py = Join-Path $t1 'server\.venv\Scripts\python.exe'
$log = Join-Path $PSScriptRoot 'build-flash.last.txt'
function Say($m, $c = 'Gray') { Write-Host $m -ForegroundColor $c; Add-Content -Path $log -Value $m }
Set-Content -Path $log -Value "=== T1 build-flash $(Get-Date -Format s) ==="

# 1. toolchain
$acli = (Get-Command arduino-cli -ErrorAction SilentlyContinue).Source
if (-not $acli) { $acli = 'E:\Program Files (x86)\ArduinoIDE\Arduino IDE\resources\app\lib\backend\resources\arduino-cli.exe' }
if (-not (Test-Path $acli)) { throw "arduino-cli not found (looked on PATH and at $acli)" }
if (-not (Test-Path $py)) { throw 'T1 server venv missing - run tools\T1-SERVER.cmd once first' }
$core = & $acli core list 2>&1 | Select-String '^esp32:esp32\s'
if (-not $core) { Say '[t1] installing esp32 core ...'; & $acli core update-index; & $acli core install esp32:esp32 }
Say "[t1] core: $($core -replace '\s+', ' ')"

# 2. generated headers
Push-Location (Join-Path $t1 'server')
$token = (& $py -m t1server device-token).Trim()
& $py -m t1server pubkey-header | Set-Content -Encoding ascii (Join-Path $sketch 'pubkey.h')
Pop-Location
if (-not $Server) {
  $ip = (Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue | Where-Object { $_.IPAddress -like '192.168.124.*' } | Select-Object -First 1).IPAddress
  if (-not $ip) { $ip = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.IPAddress -like '192.168.*' } | Select-Object -First 1).IPAddress }
  $Server = "http://${ip}:8095"
}
if (-not $Ssid) { $Ssid = Read-Host 'Wi-Fi SSID the T1 box joins (the lab H3C for testing)' }
$sec = Read-Host "Wi-Fi password for '$Ssid' (typed here, stays on this PC)" -AsSecureString
$pass = [Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($sec))
function CEsc($s) { $s -replace '\\', '\\\\' -replace '"', '\"' }
$static = ''
if ($StaticIp) {
  $gw = ($StaticIp -replace '\.\d+$', '.1')
  $static = "#define T1_STATIC_IP `"$StaticIp`"`n#define T1_GATEWAY `"$gw`"`n#define T1_SUBNET `"255.255.255.0`"`n"
}
$secrets = Join-Path $sketch 'secrets.h'
@"
// GENERATED by t1/scripts/build-flash.ps1 $(Get-Date -Format s) - git-ignored, deleted after flashing
#pragma once
#define WIFI_SSID "$(CEsc $Ssid)"
#define WIFI_PASS "$(CEsc $pass)"
#define T1_DEVICE_TOKEN "$token"
#define T1_SERVER_FALLBACK "$Server"
#define T1_DEFAULT_LEVEL "$Level"
$static
"@ | Set-Content -Encoding ascii $secrets
$pass = $null
Say "[t1] secrets.h written (SSID '$Ssid', server fallback $Server, level $Level)"

# 3. compile
# -UsbCdc for boards wired through the S3's native USB port (e.g. the COM10 lab board);
# leave it off for boards with a CH340/CP210x USB-UART chip (e.g. the COM8 lab board).
$fqbn = "esp32:esp32:esp32s3:FlashSize=16M,PSRAM=$Psram,PartitionScheme=app3M_fat9M_16MB"
if ($UsbCdc) { $fqbn += ',USBMode=hwcdc,CDCOnBoot=cdc' }
$build = Join-Path $t1 'firmware\.build'
Say "[t1] compiling $fqbn"
$out = & $acli compile --fqbn $fqbn --build-path $build --warnings default $sketch 2>&1
$out | Select-Object -Last 8 | ForEach-Object { Say "    $_" }
if ($LASTEXITCODE -ne 0) { if (-not $KeepSecrets) { Remove-Item $secrets -Force }; throw 'compile FAILED - see above' }

# 4. upload
$flashed = Get-Date
if (-not $NoUpload) {
  if (-not $Port) {
    $ports = & $acli board list --format json | ConvertFrom-Json
    $cands = @($ports.detected_ports | Where-Object { $_.port.protocol -eq 'serial' } | ForEach-Object { $_.port.address })
    if ($cands.Count -eq 1) { $Port = $cands[0] }
    else { $Port = Read-Host "Serial port of the ESP32-S3 (found: $($cands -join ', '))" }
  }
  Say "[t1] uploading to $Port (hold BOOT and tap RST if it will not connect)"
  & $acli upload --fqbn $fqbn --input-dir $build -p $Port $sketch 2>&1 | Select-Object -Last 5 | ForEach-Object { Say "    $_" }
  if ($LASTEXITCODE -ne 0) { if (-not $KeepSecrets) { Remove-Item $secrets -Force }; throw 'upload FAILED' }
}
if (-not $KeepSecrets) { Remove-Item $secrets -Force; Say '[t1] secrets.h deleted' }
if ($NoUpload) { Say '[t1] compile OK (not uploaded)' 'Green'; exit 0 }

# 5. read-back: the flash only counts once the box reports to the server
Say '[t1] waiting up to 120 s for the board to report in ...'
$deadline = (Get-Date).AddSeconds(120); $seen = $null
$since = [DateTimeOffset]::new($flashed).ToUnixTimeSeconds()
while ((Get-Date) -lt $deadline -and -not $seen) {
  Start-Sleep 5
  try { $seen = (Invoke-RestMethod http://127.0.0.1:8095/api/t1/v1/devices -TimeoutSec 5) | Where-Object { $_.first_seen -ge $since -or $_.last_seen -ge $since + 5 } | Select-Object -First 1 } catch {}
}
if ($seen) {
  Say "[t1] REPORTED: $($seen.id) at $($seen.ip) - $($seen.status_label), level $($seen.level), fw $($seen.fw)" 'Green'
  Say "[t1] next: point the router's UPSTREAM DNS at $($seen.ip) (not the DHCP DNS - ADR-001), then watch http://127.0.0.1:8095/"
} else {
  Say '[t1] the board has NOT reported in 120 s. Open the serial monitor to see why:' 'Red'
  Say "     & '$acli' monitor -p $Port -c baudrate=115200" 'Red'
  exit 1
}
