"""ECDSA P-256 signing of filter and allow-list files.

The device holds only the PUBLIC key (compiled in by the build script), so a device
that is taken apart cannot be used to forge filters for the rest of the fleet.
P-256 rather than Ed25519 because the ESP32's mbedTLS verifies P-256 natively.
The private key never leaves DATA_DIR/keys and is git-ignored with the rest of data/.
"""
from __future__ import annotations

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec

from .config import data_path

_KEY = "keys/t1-signing.pem"
_PUB = "keys/t1-signing.pub.pem"


def _load() -> ec.EllipticCurvePrivateKey:
    f = data_path(*_KEY.split("/"))
    if not f.exists():
        key = ec.generate_private_key(ec.SECP256R1())
        f.write_bytes(key.private_bytes(serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8,
                                        serialization.NoEncryption()))
        data_path(*_PUB.split("/")).write_bytes(key.public_key().public_bytes(
            serialization.Encoding.PEM, serialization.PublicFormat.SubjectPublicKeyInfo))
    return serialization.load_pem_private_key(f.read_bytes(), password=None)


def public_pem() -> str:
    _load()
    return data_path(*_PUB.split("/")).read_text()


def sign(blob: bytes) -> str:
    """DER signature over SHA-256(blob), hex - exactly what mbedtls_pk_verify takes."""
    return _load().sign(blob, ec.ECDSA(hashes.SHA256())).hex()


def verify(blob: bytes, sig_hex: str) -> bool:
    try:
        _load().public_key().verify(bytes.fromhex(sig_hex), blob, ec.ECDSA(hashes.SHA256()))
        return True
    except (InvalidSignature, ValueError):
        return False


def firmware_header() -> str:
    """pubkey.h for the sketch."""
    lines = "\n".join(f'  "{ln}\\n"' for ln in public_pem().strip().splitlines())
    return ("// GENERATED by `python -m t1server pubkey-header` - the T1 server's filter-signing\n"
            "// PUBLIC key. Not a secret. Regenerate if the server key is ever replaced.\n"
            "#pragma once\nstatic const char T1_PUBKEY_PEM[] =\n" + lines + ";\n")
