#!/usr/bin/env bash
# Read-only: for each activity-log topic, count matching commits (all branches) and show the newest.
cd /e/Gateflame || exit 1
check() { # label, regex
  n=$(git log --all -i -E --grep="$2" --format=%h | wc -l)
  last=$(git log --all -i -E --grep="$2" -1 --format='%h %ad %s' --date=short | cut -c1-110)
  printf '%-28s %3s  %s\n' "$1" "$n" "$last"
}
check "charts UI"          "chart"
check "kiosk 2GB"          "2 ?GB|kiosk.*(fit|lite|zero)"
check "lint blocklists/dpi" "lint|blocklists\.py|dpi\.py"
check "scripts C:->E:"     "C: home|scratch|moved .*tools"
check "status v8.0"        "v8\.0|status.*8\.0"
check "Antigravity"        "antigravity"
check "DoH/DoT block"      "DoH|DoT|encrypted.DNS"
check "Shield VPN"         "shield|vpn ?gate|vpngate"
check "continent picker"   "continent"
check "pairing crash"      "pairing"
check "console login"      "login"
check "fleet dashboard"    "fleet"
check "mobile redesign"    "redesign"
check "Ionibot"            "ionibot"
check "PoC v0.5"           "poc|v0\.5"
check "POPIA"              "popia|privacy notice"
check "data safety"        "data.safety"
check "prove-it.ps1"       "prove-it"
check "gravity timeout"    "gravity"
check "simulated data"     "simulat|mock"
check "node profiles"      "profile"
check "on-box ML"          "\bML\b|machine learning|on-box"
check "splash/a11y"        "splash|accessib"
check "Electron desktop"   "electron|desktop"
check "Gemini comparison"  "gemini"
check "fabricated cred"    "fabricat|credential"
check "bot prediction"     "bot predict|prediction"
check "BUG-01/02/18"       "BUG-0?1\b|BUG-0?2\b|BUG-18|X-FTL"
check "BUG-06"             "BUG-0?6"
check "BUG-19"             "BUG-19|mixed.content|allowMixed"
check "handover"           "handover"
check "live proof"         "proof"
check "Docker backend"     "docker"
check "C: reconcile"       "reconcil"
check "renumber self-heal" "renumber|self-heal"
check "inspector console"  "inspector"
check "ESP32-MCP"          "esp32"
check "H3C lab move"       "lab|h3c"
check "release v1.0.3"     "1\.0\.3"
check "probe/flash tool"   "probe|flash"
check "tiering"            "tier"
check "offline server"     "offline server|ionity server"
check "v1.1.0"             "1\.1\.0"
check "Pionex"             "pionex|grid bot"
