#!/usr/bin/env bash
# Commit the Tiers & Models document, its generator and the AEDI template. ff main.
set -u
cd /e/Gateflame || exit 1
[ "$(git config user.name)" = DennisIonity ] || { echo "WRONG IDENTITY"; exit 1; }
[ "$(git rev-parse --abbrev-ref HEAD)" = fix/mobile-dns-drops ] || { echo "wrong branch"; exit 1; }
git add .gitattributes "docs/Ionity_Gate^Flame-Tiers&Models.docx" docs/templates/TEMPLATE_2026_OFFICAL_v1.1.1.docx \
  tools/build-tiers-doc.py tools/commit-tiers-doc-2026-09-25.sh
git commit -q -m "Ionity_Gate^Flame-Tiers&Models.docx v1.0 on the AEDI template: overview, tier layout, T1/T3 Standard, T3 Premium direction, reserved slots, open decisions, recommendations; generated by tools/build-tiers-doc.py; *.docx/xlsx/pptx marked binary" \
  && git log -1 --format='committed %h %an'
git merge-base --is-ancestor main HEAD && git branch -f main HEAD && echo "main -> $(git rev-parse --short main)"
echo "unpushed: $(git log --branches --not --remotes --oneline | wc -l)"; git status --porcelain | head -3
