"""module_firewall_bounce — nftables bouncer.

Temporarily denies a misbehaving LAN host the ability to forward traffic
through the node, and lets it back on when the bounce expires.

────────────────────────────────────────────────────────────────────────────
WHY THIS FILE IS WRITTEN THE WAY IT IS
────────────────────────────────────────────────────────────────────────────
The previous implementation of this module was the worst defect in the lost
build: a caller-supplied IP was interpolated into an `nft` command, so a
crafted path parameter could reach `nft flush ruleset` and take the whole
firewall down — including, on a device sold as a security appliance, its own
protection. That bug is the reason this module was deliberately left
`not_implemented` in the clean-room rebuild rather than restored in a hurry.

Five structural choices make that class of bug unreachable here, in order of
how much they matter:

1. NO SHELL, EVER. Every invocation goes through one helper that passes an
   argv list with shell=False. There is no string that a shell ever parses,
   so shell metacharacters have no meaning no matter what arrives.

2. THE RULESET IS A CONSTANT. `_RULESET` below contains no interpolation of
   any kind — no f-string, no %, no .format(), no concatenation. It is
   installed once. Nothing at runtime ever writes a *rule*.

3. RUNTIME CHANGES ARE SET ELEMENTS ONLY. `add element` / `delete element`
   against a named set. The grammar of that command has exactly one variable
   position and it must be an address literal. Even a hypothetical parser
   confusion has nowhere to go: there is no rule body to inject into.

4. VALIDATION RE-EMITS RATHER THAN APPROVES. `_canonical()` does not check
   the caller's string and then pass the caller's string along. It parses
   with `ipaddress.ip_address()` and passes on `str(parsed)` — a value
   generated by the standard library, not by the caller. A string that
   survives parsing is by construction a bare address; `"10.0.0.5; nft flush
   ruleset"` never parses, and nothing that does parse can carry a payload.

5. DENY BY DEFAULT ON *WHAT* MAY BE BOUNCED. Validation is not only about
   syntax. Bouncing the wrong host is a self-inflicted outage: the default
   gateway cuts the whole LAN off the internet, the node's own address cuts
   the phone off the node (and would strand the kiosk with no way to undo
   it), and a public address means someone is trying to use a home appliance
   as a censorship device. All are refused with a named reason.

Two further properties are about blast radius rather than injection:

- EVERY BOUNCE EXPIRES. Elements carry an nftables `timeout`, so a bounce is
  self-healing even if the agent dies, the DB is lost, or nobody ever calls
  release. There is no way to express a permanent bounce through this API.
- THE TABLE IS ADDITIVE AND POLICY-ACCEPT. It drops only what is in the set.
  If every other assumption in this file is wrong, the failure mode is "the
  bouncer does nothing", not "the LAN goes dark".

Capability: needs CAP_NET_ADMIN. Without it the module reports `degraded`
with a named gap and remedy — it never reports `running` while silently
doing nothing, which is the house rule for every module in this agent.
"""

from __future__ import annotations

import ipaddress
import logging
import shutil
import subprocess  # noqa: S404 — argv-only, shell=False, see module docstring
import threading
from dataclasses import dataclass

logger = logging.getLogger("gateflame.firewall")

TABLE_FAMILY = "inet"
TABLE_NAME = "gateflame"
SET_V4 = "bounced_v4"
SET_V6 = "bounced_v6"

# Bounds on how long a host may be bounced. The lower bound stops a caller
# creating thousands of near-instant elements as a cheap way to churn the
# ruleset; the upper bound is what makes "self-healing" true — a day is long
# enough to be useful and short enough that a forgotten bounce resolves
# itself before anyone files a support ticket.
MIN_SECONDS = 30
MAX_SECONDS = 86_400
DEFAULT_SECONDS = 900

_NFT_TIMEOUT_SECONDS = 5.0

# ─── The ruleset. A CONSTANT. Do not interpolate anything into this. ────────
#
# policy accept + explicit drops means this table only ever subtracts from
# what is allowed, and only for addresses present in the sets. Both directions
# are dropped: dropping only saddr would let a bounced host keep receiving
# inbound connections, which is not what "bounced" means to a customer.
#
# `flags timeout` is what lets each element carry its own expiry.
_RULESET = """\
table inet gateflame {
    set bounced_v4 {
        type ipv4_addr
        flags timeout
        comment "Gate^Flame: LAN hosts temporarily denied forwarding"
    }

    set bounced_v6 {
        type ipv6_addr
        flags timeout
        comment "Gate^Flame: LAN hosts temporarily denied forwarding"
    }

    chain gateflame_forward {
        type filter hook forward priority 0; policy accept;
        ip saddr @bounced_v4 counter drop
        ip daddr @bounced_v4 counter drop
        ip6 saddr @bounced_v6 counter drop
        ip6 daddr @bounced_v6 counter drop
    }
}
"""


class FirewallRefusal(Exception):
    """A bounce was refused. `reason` is a stable machine code, `advisory` is
    the sentence shown to the customer."""

    def __init__(self, reason: str, advisory: str):
        super().__init__(f"{reason}: {advisory}")
        self.reason = reason
        self.advisory = advisory


class FirewallUnavailable(Exception):
    """nftables cannot be driven at all — missing binary or no CAP_NET_ADMIN."""

    def __init__(self, gap: str):
        super().__init__(gap)
        self.gap = gap


@dataclass(frozen=True)
class LocalContext:
    """Addresses this node must refuse to bounce.

    Injected rather than discovered inside the bounce path so the refusal
    rules are testable without a network stack, and so a discovery failure
    can never silently produce an empty protected-set (see `discover`).
    """

    own_addresses: frozenset[str]
    gateways: frozenset[str]


def _run_argv(argv: list[str], stdin_text: str | None = None) -> subprocess.CompletedProcess:
    """The only place this module executes anything.

    shell=False is the default for a list argv and is stated explicitly here
    because it is load-bearing, not incidental. A timeout is set so a wedged
    nft cannot hang an API request thread forever.
    """
    return subprocess.run(  # noqa: S603 — argv list, shell=False, absolute path asserted by caller
        argv,
        input=stdin_text,
        capture_output=True,
        text=True,
        shell=False,
        timeout=_NFT_TIMEOUT_SECONDS,
        check=False,
    )


class SubprocessNftRunner:
    """Real nft. Resolves the binary once, to an absolute path."""

    def __init__(self) -> None:
        self._path = shutil.which("nft")

    @property
    def available(self) -> bool:
        return self._path is not None

    def run(self, args: list[str], stdin_text: str | None = None) -> subprocess.CompletedProcess:
        if self._path is None:
            raise FirewallUnavailable(
                "`nft` is not on PATH — install nftables (apt install nftables)"
            )
        # The binary is the resolved absolute path, never the string "nft",
        # so the result does not depend on PATH at call time.
        return _run_argv([self._path, *args], stdin_text=stdin_text)


def _canonical(raw: object) -> ipaddress.IPv4Address | ipaddress.IPv6Address:
    """Parse to an address object, or refuse.

    The return value is a stdlib object. Callers must render it with str(),
    never touch the original input again. This is the single most important
    function in the file: it is the boundary at which caller-controlled text
    stops existing.
    """
    if not isinstance(raw, str):
        raise FirewallRefusal("invalid_address", "Address must be a string.")
    text = raw.strip()
    if not text or len(text) > 45:  # 45 = longest possible IPv6 text form
        raise FirewallRefusal("invalid_address", "Address is empty or implausibly long.")
    try:
        return ipaddress.ip_address(text)
    except ValueError:
        # Deliberately does not echo the input back. An error message is a
        # place where attacker-controlled text ends up in logs, consoles and
        # UI, and there is nothing useful in it that the caller does not
        # already know.
        raise FirewallRefusal(
            "invalid_address", "Not a valid IP address."
        ) from None


def _assert_bounceable(
    ip: ipaddress.IPv4Address | ipaddress.IPv6Address, ctx: LocalContext
) -> None:
    """Refuse the addresses where a bounce would be a self-inflicted outage,
    a no-op, or a misuse of the product."""
    if ip.is_loopback:
        raise FirewallRefusal(
            "refused_loopback", "Refusing to bounce loopback — that is this node itself."
        )
    if ip.is_multicast:
        raise FirewallRefusal(
            "refused_multicast", "Multicast is not a host and cannot be bounced."
        )
    if ip.is_unspecified:
        raise FirewallRefusal(
            "refused_unspecified", "0.0.0.0 / :: is not a host and cannot be bounced."
        )
    if not (ip.is_private or ip.is_link_local):
        # A Gate^Flame node protects one LAN. Bouncing a public address is
        # either a mistake or an attempt to use the appliance to block a site
        # for someone else's network — the DNS filter is the supported way to
        # block a destination, and it is auditable.
        raise FirewallRefusal(
            "refused_not_lan",
            "Only LAN hosts can be bounced. Use DNS filtering to block internet destinations.",
        )
    text = str(ip)
    if text in ctx.own_addresses:
        raise FirewallRefusal(
            "refused_self",
            "Refusing to bounce this node — it would cut every paired phone off from it.",
        )
    if text in ctx.gateways:
        raise FirewallRefusal(
            "refused_gateway",
            "Refusing to bounce the default gateway — it would take the whole network offline.",
        )


def _clamp_seconds(seconds: object) -> int:
    if isinstance(seconds, bool) or not isinstance(seconds, int):
        raise FirewallRefusal("invalid_duration", "Duration must be a whole number of seconds.")
    return max(MIN_SECONDS, min(MAX_SECONDS, seconds))


class Firewall:
    """Bounce controller. One per process; `services.py` owns the instance."""

    def __init__(self, runner=None, context_provider=None):
        self._runner = runner if runner is not None else SubprocessNftRunner()
        self._context_provider = context_provider or discover_local_context
        self._lock = threading.Lock()
        self._installed = False

    # ── capability ────────────────────────────────────────────────────────

    def capability(self) -> tuple[bool, str | None]:
        """(usable, gap). Never raises — this is called from status paths."""
        if not getattr(self._runner, "available", True):
            return False, "`nft` is not on PATH — install nftables (apt install nftables)"
        try:
            result = self._runner.run(["--version"])
        except Exception as exc:  # noqa: BLE001 — a status call must not throw
            return False, f"nftables is not usable: {exc}"
        if result.returncode != 0:
            return False, "nftables is installed but `nft --version` failed"
        try:
            probe = self._runner.run(["list", "ruleset"])
        except Exception as exc:  # noqa: BLE001
            return False, f"nftables is not usable: {exc}"
        if probe.returncode != 0:
            return (
                False,
                "no CAP_NET_ADMIN — grant it to the unit "
                "(AmbientCapabilities=CAP_NET_ADMIN in gateflame.service), never run as root",
            )
        return True, None

    # ── ruleset lifecycle ─────────────────────────────────────────────────

    def ensure_installed(self) -> None:
        with self._lock:
            if self._installed:
                return
            usable, gap = self.capability()
            if not usable:
                raise FirewallUnavailable(gap or "nftables unavailable")
            # `nft -f -` with a constant on stdin. Not a template.
            result = self._runner.run(["-f", "-"], stdin_text=_RULESET)
            if result.returncode != 0:
                raise FirewallUnavailable(
                    f"could not install the gateflame table: {result.stderr.strip()[:200]}"
                )
            self._installed = True

    def teardown(self) -> None:
        """Remove the table entirely. Releases every bounce at once, which is
        the correct behaviour when the module is stopped: a stopped bouncer
        must not keep silently dropping traffic."""
        try:
            self._runner.run(["delete", "table", TABLE_FAMILY, TABLE_NAME])
        except Exception:  # noqa: BLE001 — teardown is best-effort
            logger.exception("firewall teardown failed")
        finally:
            with self._lock:
                self._installed = False

    # ── the operations ────────────────────────────────────────────────────

    def bounce(self, address: object, seconds: object = DEFAULT_SECONDS) -> dict:
        ip = _canonical(address)
        ctx = self._context_provider()
        _assert_bounceable(ip, ctx)
        duration = _clamp_seconds(seconds)
        self.ensure_installed()

        set_name = SET_V4 if ip.version == 4 else SET_V6
        # str(ip) — the stdlib's rendering, not the caller's text.
        element = "{ " + str(ip) + " timeout " + str(duration) + "s }"
        result = self._runner.run(
            ["add", "element", TABLE_FAMILY, TABLE_NAME, set_name, element]
        )
        if result.returncode != 0:
            raise FirewallUnavailable(
                f"nft rejected the element: {result.stderr.strip()[:200]}"
            )
        logger.info("bounced %s for %ss", ip, duration)
        return {"address": str(ip), "seconds": duration}

    def release(self, address: object) -> dict:
        ip = _canonical(address)
        self.ensure_installed()
        set_name = SET_V4 if ip.version == 4 else SET_V6
        result = self._runner.run(
            ["delete", "element", TABLE_FAMILY, TABLE_NAME, set_name, "{ " + str(ip) + " }"]
        )
        # A release of something not bounced is success, not an error — the
        # caller's intent ("this host must not be bounced") is satisfied, and
        # an element may have expired on its own a moment earlier.
        released = result.returncode == 0
        return {"address": str(ip), "released": released}

    def bounced(self) -> list[dict]:
        """Read the live set back out of the kernel.

        Read from nftables rather than from an in-process dict: elements
        expire in the kernel, so any cached copy starts lying the moment a
        timeout fires. The kernel is the only honest source.
        """
        try:
            self.ensure_installed()
        except FirewallUnavailable:
            return []
        out: list[dict] = []
        for set_name in (SET_V4, SET_V6):
            result = self._runner.run(
                ["-j", "list", "set", TABLE_FAMILY, TABLE_NAME, set_name]
            )
            if result.returncode != 0:
                continue
            out.extend(_parse_set_json(result.stdout))
        return out


def _parse_set_json(text: str) -> list[dict]:
    """Parse `nft -j list set` output.

    Tolerant by design: a parse failure here must degrade to "I cannot tell
    you what is bounced", never to an exception on a read-only status route.
    """
    import json

    try:
        doc = json.loads(text)
    except (ValueError, TypeError):
        return []
    if not isinstance(doc, dict):
        return []
    nodes = doc.get("nftables")
    if not isinstance(nodes, list):
        return []
    found: list[dict] = []
    for node in nodes:
        if not isinstance(node, dict):
            continue
        set_node = node.get("set")
        if not isinstance(set_node, dict):
            continue
        elems = set_node.get("elem")
        if not isinstance(elems, list):
            continue
        for elem in elems:
            if isinstance(elem, str):
                found.append({"address": elem, "expiresInSeconds": None})
            elif isinstance(elem, dict):
                inner = elem.get("elem")
                if not isinstance(inner, dict):
                    continue
                value = inner.get("val")
                if isinstance(value, str):
                    found.append(
                        {"address": value, "expiresInSeconds": inner.get("expires")}
                    )
    return found


def discover_local_context() -> LocalContext:
    """Find this node's own addresses and its default gateways.

    Fails CLOSED. If discovery breaks, this raises rather than returning an
    empty protected-set — an empty set would silently make "never bounce the
    gateway" stop being true, which is exactly the outage this guard exists
    to prevent. Refusing to bounce anything is the safe direction.
    """
    own: set[str] = set()
    gateways: set[str] = set()
    try:
        import psutil

        for addrs in psutil.net_if_addrs().values():
            for addr in addrs:
                try:
                    own.add(str(ipaddress.ip_address(addr.address.split("%")[0])))
                except (ValueError, AttributeError):
                    continue
    except Exception as exc:  # noqa: BLE001
        raise FirewallUnavailable(f"cannot enumerate local addresses: {exc}") from exc

    ip_bin = shutil.which("ip")
    if ip_bin is None:
        raise FirewallUnavailable("`ip` (iproute2) is not on PATH — cannot identify the gateway")
    for family in ("-4", "-6"):
        try:
            result = _run_argv([ip_bin, family, "route", "show", "default"])
        except Exception:  # noqa: BLE001
            continue
        if result.returncode != 0:
            continue
        for line in result.stdout.splitlines():
            parts = line.split()
            if "via" in parts:
                candidate = parts[parts.index("via") + 1]
                try:
                    gateways.add(str(ipaddress.ip_address(candidate.split("%")[0])))
                except (ValueError, IndexError):
                    continue

    if not own:
        raise FirewallUnavailable("no local addresses found — refusing to operate blind")
    return LocalContext(own_addresses=frozenset(own), gateways=frozenset(gateways))
