// Gate^Flame T1 node - compile-time settings. Secrets are NOT here: see secrets.h
// (generated by t1/scripts/build-flash.ps1, git-ignored) and pubkey.h (generated).
#pragma once

#define FW_VERSION          "0.1.0"
#define FW_PRODUCT          "GateFlame-T1"

#define DNS_PORT            53
#define PENDING_SLOTS       96       // in-flight upstream queries
#define UPSTREAM_RESEND_MS  1200     // no answer from upstream 1 -> ask upstream 2
#define UPSTREAM_GIVEUP_MS  3000     // then SERVFAIL, so the router uses its own upstream
#define DEGRADED_AFTER_MS   15000    // upstream silent this long while queries wait -> degraded

#define TELEMETRY_MS        30000
#define UPDATE_CHECK_MS     (6UL * 3600UL * 1000UL)
#define REDISCOVER_AFTER    5        // failed reports before looking for the server again

// Default upstream resolvers. NEVER the router: the router forwards to us, so
// forwarding back to it would loop. Quad9 also blocks malware on its side.
#define DEFAULT_UPSTREAM_1  "9.9.9.9"
#define DEFAULT_UPSTREAM_2  "149.112.112.112"

#define ALLOW_MAX           4096
#define NET_TASK_STACK      16384
